apiVersion: v1
kind: Pod
metadata: 
  name: phpinfo-po
spec:
  containers:
    - 
      args:
      command:
      env:
      image:
      name:
      ports:
      volumeMounts:
      workingDir:
    
  initContainers:
  volumes:
